# Sales Performance Dashboard(Data Layer)

#### Importing library and dataset

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Superstore.csv", encoding="latin-1")

#### Understanding GroupBy & Finding Total Sales by Region

In [4]:
df.head()
df.groupby("Region")["Sales"].sum()

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

#### Multiple Grouping

In [5]:
df.groupby(["Region", "Category"])[["Sales", "Profit"]].sum()

                               Sales      Profit
Region  Category
Central Furniture        163797.1638  -2871.0494
        Office Supplies  167026.4150   8879.9799
        Technology       170416.3120  33697.4320
East    Furniture        208291.2040   3046.1658
        Office Supplies  205516.0550  41014.5791
        Technology       264973.9810  47462.0351
South   Furniture        117298.6840   6771.2061
        Office Supplies  125651.3130  19986.3928
        Technology       148771.9080  19991.8314
West    Furniture        252612.7435  11504.9503
        Office Supplies  220853.2490  52609.8490
        Technology       251991.8320  44303.6496

#### Understanding Aggregation

In [6]:
df.groupby("Region").agg({
    "Sales": ["sum", "mean", "max"],
    "Profit": ["sum", "mean"]
})

               Sales                              Profit
                 sum        mean        max          sum       mean
Region
Central  501239.8908  215.772661  17499.950   39706.3625  17.092709
East     678781.2400  238.336110  11199.968   91522.7800  32.135808
South    391721.9050  241.803645  22638.480   46749.4303  28.857673
West     725457.8245  226.493233  13999.960  108418.4489  33.849032

#### Top 3 Sub-Categorries Per Region

In [7]:
subcat_sales = df.groupby(
    ["Region", "Sub-Category"]
)["Sales"].sum()

In [8]:
subcat_sales = subcat_sales.sort_values(ascending=False)

In [9]:
top3 = subcat_sales.groupby(level=0).head(3)
top3

Region   Sub-Category
West     Chairs          101781.328
East     Phones          100614.982
West     Phones           98684.352
East     Chairs           96260.683
Central  Chairs           85230.646
West     Tables           84754.562
Central  Phones           72403.282
East     Storage          71612.584
South    Phones           58304.438
Central  Binders          56923.282
South    Machines         53890.960
         Chairs           45176.446
Name: Sales, dtype: float64

#### Add New Column

In [10]:
df["Profit Margin %"] = (
    df["Profit"] / df["Sales"]
) * 100

#### Pivot Tables

In [11]:
pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Segment",
    aggfunc="mean"
)

#### Loss making month calculations

In [12]:
# Datetime conversion
df["Order Date"] = pd.to_datetime(
    df["Order Date"]
)

# Monthly profit
df["Month"] = df["Order Date"].dt.month

monthly_profit = df.groupby(
    "Month"
)["Profit"].sum()

loss_months = monthly_profit[
    monthly_profit < 0
]

print(loss_months)

# Quarterly sales
df = df.set_index("Order Date")

quarterly_sales = df["Sales"].resample(
    "Q"
).sum()

print(quarterly_sales)

Series([], Name: Profit, dtype: float64)
Order Date
2014-03-31     74447.7960
2014-06-30     86538.7596
2014-09-30    143633.2123
2014-12-31    179627.7302
2015-03-31     68851.7386
2015-06-30     89124.1870
2015-09-30    130259.5752
2015-12-31    182297.0082
2016-03-31     93237.1810
2016-06-30    136082.3010
2016-09-30    143787.3622
2016-12-31    236098.7538
2017-03-31    123144.8602
2017-06-30    133764.3720
2017-09-30    196251.9560
2017-12-31    280054.0670
Freq: QE-DEC, Name: Sales, dtype: float64

C:\Users\HP\AppData\Local\Temp\ipykernel_20796\850026995.py:22: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  quarterly_sales = df["Sales"].resample(