# Database Handling using SQLite

In [3]:
import sqlite3

# Create/connect database
conn = sqlite3.connect("company_master.db")

print("Database Connected")

Database Connected

In [4]:
cursor = conn.cursor()

In [7]:
import pandas as pd
employees_df=pd.read_sql_query("SELECT * FROM employees", conn)

In [8]:
employees_df.head()

,employee_id,first_name,last_name,email,phone,age,gender,department,salary,city,state,country,joining_date,experience_years,performance_score
0,1,Craig,Hernandez,joseschroeder@gallegos.com,+1-003-413-3743x8511,50,Female,Operations,56741,Raytown,Massachusetts,India,2018-06-08,17,4.01
1,2,Amber,Peterson,kross@yahoo.com,001-048-976-7601x319,51,Female,Marketing,136469,West James,Rhode Island,India,2024-08-10,13,1.52
2,3,Miranda,Thompson,estescynthia@yahoo.com,001-514-088-2135x2319,41,Female,Marketing,67379,Porterborough,Wyoming,India,2023-07-29,14,1.30
3,4,Lori,Ross,diana77@russo.org,231-402-9969x84520,50,Female,Operations,149857,Reneeland,Wyoming,India,2021-03-28,1,3.07
4,5,Phillip,Romero,maryaguilar@lee.com,357.687.2021x59685,42,Female,Finance,62198,East Andreafurt,Nebraska,India,2025-02-27,5,3.76

In [9]:
conn2=sqlite3.connect("project_records.db")

In [10]:
projects_df = pd.read_sql_query(
    "SELECT * FROM projects",
    conn2
)

print(projects_df.head())

   project_id  employee_id  manager_employee_id project_name  \
0           1           70                   62    Project_1
1           2           12                   91    Project_2
2           3            1                   49    Project_3
3           4           62                   79    Project_4
4           5           90                   23    Project_5

               client_name  budget  duration_months       status technology  \
0             Russell-Hull  798243               15  In Progress       Java
1  Rogers, Ford and Nelson  229045               14      Pending        SQL
2               Mccann Ltd  804414               18    Completed     Python
3          Mitchell-Bailey  179837               17    Completed      React
4                  Fry-Cox  451072               24    Completed      AI/ML

   start_date    end_date  team_size
0  2025-06-17  2026-10-22          4
1  2024-04-18  2027-05-20         12
2  2022-06-06  2028-01-05         16
3  2025-10-01  2026-07-05          3
4  2025-04-15  2027-01-30         11

In [11]:
merged_df=pd.merge(employees_df, projects_df, on="employee_id", how="inner")

In [12]:
merged_df

,employee_id,first_name,last_name,email,phone,age,gender,department,salary,city,...,manager_employee_id,project_name,client_name,budget,duration_months,status,technology,start_date,end_date,team_size
0,1,Craig,Hernandez,joseschroeder@gallegos.com,+1-003-413-3743x8511,50,Female,Operations,56741,Raytown,...,49,Project_3,Mccann Ltd,804414,18,Completed,Python,2022-06-06,2028-01-05,16
1,3,Miranda,Thompson,estescynthia@yahoo.com,001-514-088-2135x2319,41,Female,Marketing,67379,Porterborough,...,49,Project_32,Arnold-Hess,988944,13,Pending,AI/ML,2025-04-17,2027-12-09,14
2,4,Lori,Ross,diana77@russo.org,231-402-9969x84520,50,Female,Operations,149857,Reneeland,...,27,Project_8,Lee Ltd,319448,24,In Progress,SQL,2026-05-03,2026-09-15,17
3,4,Lori,Ross,diana77@russo.org,231-402-9969x84520,50,Female,Operations,149857,Reneeland,...,85,Project_53,Gutierrez and Sons,214711,14,Completed,AI/ML,2026-01-23,2026-09-04,16
4,9,Corey,Parker,dustinmartinez@yahoo.com,616-011-8398x269,25,Female,Operations,64980,North Ryanmouth,...,59,Project_38,Mckay-Davenport,351472,18,Completed,Java,2021-12-31,2028-05-06,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Sarah,Copeland,deleonmichael@hotmail.com,607-717-4926x500,31,Female,Finance,96461,North Joan,...,19,Project_66,Noble-Bailey,792745,3,Pending,Python,2022-07-22,2028-03-20,10
96,96,Sarah,Bender,obrown@clark.com,(536)184-7017x9922,43,Male,IT,146879,Cartermouth,...,24,Project_61,Garcia-Schmidt,614363,16,Pending,Java,2026-03-20,2027-08-04,11
97,97,Kimberly,Brooks,daniel56@williams.com,001-857-484-5728x2668,52,Male,Operations,68054,Nelsonborough,...,28,Project_58,Farley Group,637984,20,Pending,Python,2022-07-21,2026-10-17,16
98,98,Sergio,Maxwell,jacqueline86@yahoo.com,156.071.0563x00675,27,Female,Finance,102288,West Brianville,...,90,Project_81,"Ward, Abbott and Johnson",100578,5,Completed,Python,2025-06-23,2026-06-07,7
99,100,Norma,Jenkins,scottdudley@yahoo.com,0374523569,35,Male,Marketing,80004,East Jenniferport,...,26,Project_100,"Newton, Lozano and Johnson",693975,5,In Progress,SQL,2024-07-09,2027-11-22,9